# Docker Compose untuk Production
# Gunakan: docker-compose up --build
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
      - ./static:/app/static
      - ./dataset:/app/dataset
      - ./templates:/app/templates
    environment:
      - FLASK_DEBUG=0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
