services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./database:/app/database
      - ./static:/app/static
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
